before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
bundler_args: --without development production --quiet
env:
  global:
    DEFAULT_MAX_WAIT_TIME: 10
  matrix:
    - GEM=api DB=mysql
    - GEM=api DB=postgres
    - GEM=backend DB=mysql
    - GEM=backend DB=postgres
    - GEM=core DB=mysql
    - GEM=core DB=postgres
    - GEM=frontend DB=mysql
    - GEM=frontend DB=postgres
    - GEM=sample DB=mysql
    - GEM=sample DB=postgres
    - GEM=backend:js
before_install:
  - gem install chromedriver-helper
script:
  - bundle exec rake spec:$GEM
rvm:
  - 2.3.5
