cache:
  - bundler
  - directories:
    - "travis_phantomjs"
before_install:
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
bundler_args: --without development production --quiet
env:
  global:
    DEFAULT_MAX_WAIT_TIME: 10
  matrix:
    - GEM=api DB=mysql
    - GEM=api DB=postgres
    - GEM=backend DB=mysql
    - GEM=backend DB=postgres
    - GEM=core DB=mysql
    - GEM=core DB=postgres
    - GEM=frontend DB=mysql
    - GEM=frontend DB=postgres
    - GEM=sample DB=mysql
    - GEM=sample DB=postgres
script:
  - bundle exec rake test_app
  - bundle exec rake spec
rvm:
  - 2.3.0
